# Generated by Django 4.0.6 on 2022-09-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Sarlavha:')),
                ('image', models.ImageField(upload_to='')),
                ('category', models.CharField(choices=[('1', 'Mahalliy'), ('2', 'Dunyo'), ('3', 'Moliya'), ('4', 'Sport'), ('5', 'FanTexnika')], default=1, max_length=35)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField(verbose_name='Maqola matni:')),
                ('blog_view', models.IntegerField(default=0)),
            ],
        ),
    ]
