# Generated by Django 4.0.6 on 2022-09-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='category',
            field=models.CharField(choices=[('1', 'Mahalliy'), ('2', 'Dunyo'), ('3', 'Moliya'), ('4', 'Sport'), ('5', 'FanTexnika'), ('6', 'Barchasi')], default=1, max_length=35),
        ),
    ]
